"""
This type stub file was generated by pyright.
"""

import beaupy.spinners as spinners
from beaupy._beaupy import Config, DefaultKeys, confirm, console, prompt, select, select_multiple
from beaupy._internals import Abort, ConversionError, ValidationError
