"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, List, Optional, Tuple, Type, TypeVar, Union
from beaupy._internals import TargetType

"""
A Python library of interactive CLI elements you have been looking for
"""
__license__ = ...
console = ...
class DefaultKeys:
    """A map of default keybindings.

    Attributes:
        escape(List[Union[Tuple[int, ...], str]]): Keys that escape the current context.
        select(List[Union[Tuple[int, ...], str]]): Keys that trigger list element selection.
        confirm(List[Union[Tuple[int, ...], str]]): Keys that trigger list confirmation.
        backspace(List[Union[Tuple[int, ...], str]]): Keys that trigger deletion of the previous character.
        delete(List[Union[Tuple[int, ...], str]]): Keys that trigger deletion of the next character.
        down(List[Union[Tuple[int, ...], str]]): Keys that select the element below.
        up(List[Union[Tuple[int, ...], str]]): Keys that select the element above.
        left(List[Union[Tuple[int, ...], str]]): Keys that select the element to the left.
        right(List[Union[Tuple[int, ...], str]]): Keys that select the element to the right.
        home(List[Union[Tuple[int, ...], str]]): Keys that move to the beginning of the context.
        end(List[Union[Tuple[int, ...], str]]): Keys that move to the end of the context.
    """
    escape: List[Union[Tuple[int, ...], str]] = ...
    select: List[Union[Tuple[int, ...], str]] = ...
    confirm: List[Union[Tuple[int, ...], str]] = ...
    backspace: List[Union[Tuple[int, ...], str]] = ...
    delete: List[Union[Tuple[int, ...], str]] = ...
    down: List[Union[Tuple[int, ...], str]] = ...
    up: List[Union[Tuple[int, ...], str]] = ...
    left: List[Union[Tuple[int, ...], str]] = ...
    right: List[Union[Tuple[int, ...], str]] = ...
    tab: List[Union[Tuple[int, ...], str]] = ...
    home: List[Union[Tuple[int, ...], str]] = ...
    end: List[Union[Tuple[int, ...], str]] = ...
    interrupt: List[Union[Tuple[int, ...], str]] = ...
    select_all: List[Union[Tuple[int, ...], str]] = ...


class Config:
    """A map of default configuration

    Attributes:
        raise_on_interrupt(bool): If True, functions will raise KeyboardInterrupt whenever one is encountered when waiting for input,
        otherwise, they will return some sane alternative to their usual return. For `select`, `prompt` and `confirm` this means `None`,
        while for `select_multiple` it means an empty list - `[]`. Defaults to False.
        raise_on_escape(bool): If True, functions will raise Abort whenever the escape key is encountered when waiting for input, otherwise,
        they will return some sane alternative to their usual return. For `select`, `prompt` and `confirm` this means `None`, while for
        `select_multiple` it means an empty list - `[]`.  Defaults to False.
        transient(bool): If False, elements will remain displayed after their context has ended. Defaults to True.
    """
    raise_on_interrupt: bool = ...
    raise_on_escape: bool = ...
    transient: bool = ...


_navigation_keys = ...
def prompt(prompt: str, target_type: Type[TargetType] = ..., validator: Callable[[TargetType], bool] = ..., secure: bool = ..., raise_validation_fail: bool = ..., raise_type_conversion_fail: bool = ..., initial_value: Optional[str] = ..., completion: Optional[Callable[[str], List[str]]] = ...) -> TargetType:
    """Function that prompts the user for written input

    Args:
        prompt (str): The prompt that will be displayed
        target_type (Union[Type[T], Type[str]], optional): Type to convert the answer to. Defaults to str.
        validator (Callable[[Any], bool], optional): Optional function to validate the input. Defaults to lambda input: True.
        secure (bool, optional): If True, input will be hidden. Defaults to False.
        raise_validation_fail (bool, optional): If True, invalid inputs will raise `rich.internals.ValidationError`, else
                                                the error will be reported onto the console. Defaults to True.
        raise_type_conversion_fail (bool, optional): If True, invalid inputs will raise `rich.internals.ConversionError`, else
                                                     the error will be reported onto the console. Defaults to True.
        initial_value (str, optional): If present, the value is placed in the prompt as the default value.

    Raises:
        ValidationError: Raised if validation with provided validator fails
        ConversionError: Raised if the value cannot be converted to provided type
        KeyboardInterrupt: Raised when keyboard interrupt is encountered and Config.raise_on_interrupt is True

    Returns:
        Union[T, str]: Returns a value formatted as provided type or string if no type is provided
    """
    ...

T = TypeVar('T')
def select(options: List[Union[str, T]], preprocessor: Callable[[T], str] = ..., cursor: str = ..., cursor_style: str = ..., cursor_index: int = ..., return_index: bool = ..., strict: bool = ..., pagination: bool = ..., page_size: int = ...) -> Union[int, Any, None]:
    """A prompt that allows selecting one option from a list of options

    Args:
        options (List[Union[str, T]]): A list of options to select from. If `preprocessor` is left as default (not passed),
                                       it needs to be a list of strings or objects with a `__str__` method. Otherwise,
                                       you can pass a `preprocessor` to create a string representation of arbitrary data-structures.
        preprocessor (Callable[[T], str]): A callable that can be used to preprocess the list of options prior to printing.
                                           For example, if you passed a `Person` object with `name` attribute, preprocessor
                                           could be `lambda person: person.name` to just show the content of `name` attribute
                                           in the select dialog. Defaults to `lambda val: val`
        cursor (str, optional): Cursor that is going to appear in front of currently selected option. Defaults to '> '.
        cursor_style (str, optional): Rich friendly style for the cursor. Defaults to 'pink1'.
        cursor_index (int, optional): Option can be preselected based on its list index. Defaults to 0.
        return_index (bool, optional): If `True`, `select` will return the index of selected element in options. Defaults to `False`.
        strict (bool, optional): If empty `options` is provided and strict is `False`, None will be returned,
        if it's `True`, `ValueError` will be thrown. Defaults to False.
        pagination (bool, optional): If `True`, pagination will be used. Defaults to False.
        page_size (int, optional): Number of options to show on a single page if pagination is enabled. Defaults to 5.

    Raises:
        ValueError: Thrown if no `options` are provided and strict is `True`
        KeyboardInterrupt: Raised when keyboard interrupt is encountered and Config.raise_on_interrupt is True

    Returns:
        Union[int, str, None]: Selected value or the index of a selected option or `None`
    """
    ...

def select_multiple(options: List[Union[str, T]], preprocessor: Callable[[T], str] = ..., tick_character: str = ..., tick_style: str = ..., cursor_style: str = ..., ticked_indices: Optional[List[int]] = ..., cursor_index: int = ..., minimal_count: int = ..., maximal_count: Optional[int] = ..., return_indices: bool = ..., strict: bool = ..., pagination: bool = ..., page_size: int = ...) -> List[Union[int, Any]]:
    """A prompt that allows selecting multiple options from a list of options

    Args:
        options (List[Union[str, T]]): A list of options to select from. If `preprocessor` is left as default (not passed),
                                       it needs to be a list of strings or objects with a `__str__` method. Otherwise,
                                       you can pass a `preprocessor` to create a string representation of arbitrary data-structures.
        preprocessor (Callable[[T], str]): A callable that can be used to preprocess the list of options prior to printing.
                                           For example, if you passed a `Person` object with `name` attribute, preprocessor
                                           could be `lambda person: person.name` to just show the content of `name` attribute
                                           in the select_multiple dialog. Defaults to `lambda val: val`
        tick_character (str, optional): Character that will be used as a tick in a checkbox. Defaults to 'x'.
        tick_style (str, optional): Rich friendly style for the tick character. Defaults to 'pink1'.
        cursor_style (str, optional): Rich friendly style for the option when the cursor is currently on it. Defaults to 'pink1'.
        ticked_indices (Optional[List[int]], optional): Indices of options that are pre-ticked when the prompt appears. Defaults to None.
        cursor_index (int, optional): Index of the option cursor starts at. Defaults to 0.
        minimal_count (int, optional): Minimal count of options that need to be selected. Defaults to 0.
        maximal_count (Optional[int], optional): Maximal count of options that need to be selected. Defaults to None.
        return_indices (bool, optional): If `True`, `select_multiple` will return the indices
                                         of ticked elements in options. Defaults to `False`.
        strict (bool, optional): If empty `options` is provided and strict is `False`, None will be returned,
                                 if it's `True`, `ValueError` will be thrown. Defaults to False.
        pagination (bool, optional): If `True`, pagination will be used. Defaults to False.
        page_size (int, optional): Number of options to show on a single page if pagination is enabled. Defaults to 5.

    Raises:
        KeyboardInterrupt: Raised when keyboard interrupt is encountered and Config.raise_on_interrupt is True

    Returns:
        Union[List[str], List[int]]: A list of selected values or indices of selected options
    """
    ...

def confirm(question: str, yes_text: str = ..., no_text: str = ..., has_to_match_case: bool = ..., enter_empty_confirms: bool = ..., default_is_yes: bool = ..., cursor: str = ..., cursor_style: str = ..., char_prompt: bool = ...) -> Optional[bool]:
    """A prompt that asks a question and offers two responses

    Args:
        question (str): Question to be asked
        yes_text (str, optional): Text of the positive response. Defaults to 'Yes'.
        no_text (str, optional): Text of the negative response. Defaults to 'No'.
        has_to_match_case (bool, optional): Check if typed response matches case. Defaults to False.
        enter_empty_confirms (bool, optional): No response is confirmation. Defaults to True.
        default_is_yes (bool, optional): Default is Yes. Defaults to False.
        cursor (str, optional): What character(s) to use as a cursor. Defaults to '> '.
        cursor_style (str, optional): Rich friendly style for the cursor. Defaults to 'pink1'.
        char_prompt (bool, optional): Print [Y/n] after the question. Defaults to True.

    Raises:
        KeyboardInterrupt: Raised when keyboard interrupt is encountered and Config.raise_on_interrupt is True

    Returns:
        Optional[bool]
    """
    ...
