"""
This type stub file was generated by pyright.
"""

from typing import Any
from yakh.key import Key

TargetType = Any
class ValidationError(Exception):
    ...


class ConversionError(Exception):
    ...


class Abort(Exception):
    key: Key
    def __init__(self, key: Key) -> None:
        ...
